# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{messed}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Hull"]
  s.date = %q{2010-02-22}
  s.default_executable = %q{messed}
  s.description = %q{A framework for short message paradigms}
  s.email = %q{joshbuddy@gmail.com}
  s.executables = ["messed"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "application_spec/Rakefile",
    "application_spec/app/runner.rb",
    "application_spec/bin/runner",
    "application_spec/bin/status",
    "application_spec/bin/web",
    "application_spec/config/environment.rb",
    "application_spec/config/environments/development.rb",
    "application_spec/log/development.log",
    "application_spec/spec/application_spec.rb",
    "application_spec/spec/spec.opts",
    "application_spec/spec/spec_helper.rb",
    "bin/messed",
    "lib/messed.rb",
    "lib/messed/booter.rb",
    "lib/messed/configuration.rb",
    "lib/messed/controller.rb",
    "lib/messed/controller/helper.rb",
    "lib/messed/controller/processing.rb",
    "lib/messed/controller/respond.rb",
    "lib/messed/em_runner.rb",
    "lib/messed/interface.rb",
    "lib/messed/interface/adapter.rb",
    "lib/messed/interface/adapter/sms.rb",
    "lib/messed/interface/adapter/twitter_consumer.rb",
    "lib/messed/interface/adapter/twitter_search.rb",
    "lib/messed/interface/adapter/twitter_sender.rb",
    "lib/messed/interface/adapter/twitter_streaming.rb",
    "lib/messed/interface/runner.rb",
    "lib/messed/logger.rb",
    "lib/messed/matcher.rb",
    "lib/messed/message.rb",
    "lib/messed/message/twitter.rb",
    "lib/messed/queue.rb",
    "lib/messed/queue/beanstalk.rb",
    "lib/messed/session.rb",
    "lib/messed/session/memcache.rb",
    "lib/messed/tasks.rb",
    "lib/messed/tasks/console.rb",
    "lib/messed/tasks/generation.rb",
    "lib/messed/tasks/runner.rb",
    "lib/messed/tasks/status.rb",
    "lib/messed/util/remote_status.rb",
    "patterns/messed/Pattern",
    "patterns/messed/Rakefile",
    "patterns/messed/app/runner.rb",
    "patterns/messed/bin/console",
    "patterns/messed/bin/runner",
    "patterns/messed/bin/status",
    "patterns/messed/bin/web",
    "patterns/messed/config/environment.rb",
    "patterns/messed/config/environments/development.rb",
    "patterns/messed/config/environments/production.rb",
    "patterns/messed/config/environments/test.rb",
    "patterns/messed/spec/application_spec.rb",
    "patterns/messed/spec/spec.opts",
    "patterns/messed/spec/spec_helper.rb",
    "spec/adapter/applications/twitter_search/app/application.rb",
    "spec/adapter/applications/twitter_search/app/runner.rb",
    "spec/adapter/applications/twitter_search/bin/incoming",
    "spec/adapter/applications/twitter_search/bin/runner",
    "spec/adapter/applications/twitter_search/bin/status",
    "spec/adapter/applications/twitter_search/config/environment.rb",
    "spec/adapter/applications/twitter_search/config/environments/development.rb",
    "spec/adapter/applications/twitter_search/log/development.log",
    "spec/adapter/applications/twitter_sender/app/application.rb",
    "spec/adapter/applications/twitter_sender/app/runner.rb",
    "spec/adapter/applications/twitter_sender/bin/incoming",
    "spec/adapter/applications/twitter_sender/bin/runner",
    "spec/adapter/applications/twitter_sender/bin/status",
    "spec/adapter/applications/twitter_sender/config/environment.rb",
    "spec/adapter/applications/twitter_sender/config/environments/development.rb",
    "spec/adapter/applications/twitter_sender/log/development.log",
    "spec/adapter/http/direct_message",
    "spec/adapter/http/twitter_search",
    "spec/adapter/http/update",
    "spec/adapter/twitter_search_spec.rb",
    "spec/adapter/twitter_sender_spec.rb",
    "spec/booter_spec.rb",
    "spec/fixtures/booter/app/application.rb",
    "spec/fixtures/booter/app/runner.rb",
    "spec/fixtures/booter/bin/incoming",
    "spec/fixtures/booter/bin/runner",
    "spec/fixtures/booter/bin/status",
    "spec/fixtures/booter/config/environment.rb",
    "spec/fixtures/booter/config/environments/development.rb",
    "spec/fixtures/booter/log/development.log",
    "spec/message_spec.rb",
    "spec/session_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/joshbuddy/messed}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A framework for short message paradigms}
  s.test_files = [
    "spec/adapter/applications/twitter_search/app/application.rb",
    "spec/adapter/applications/twitter_search/app/runner.rb",
    "spec/adapter/applications/twitter_search/config/environment.rb",
    "spec/adapter/applications/twitter_search/config/environments/development.rb",
    "spec/adapter/applications/twitter_sender/app/application.rb",
    "spec/adapter/applications/twitter_sender/app/runner.rb",
    "spec/adapter/applications/twitter_sender/config/environment.rb",
    "spec/adapter/applications/twitter_sender/config/environments/development.rb",
    "spec/adapter/twitter_search_spec.rb",
    "spec/adapter/twitter_sender_spec.rb",
    "spec/booter_spec.rb",
    "spec/fixtures/booter/app/application.rb",
    "spec/fixtures/booter/app/runner.rb",
    "spec/fixtures/booter/config/environment.rb",
    "spec/fixtures/booter/config/environments/development.rb",
    "spec/message_spec.rb",
    "spec/session_spec.rb",
    "spec/spec_helper.rb",
    "test/app/runner.rb",
    "test/config/environment.rb",
    "test/config/environments/development.rb",
    "test/config/environments/production.rb",
    "test/config/environments/test.rb",
    "test/spec/application_spec.rb",
    "test/spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
      s.add_runtime_dependency(%q<em-http-request>, [">= 0.2.6"])
      s.add_runtime_dependency(%q<em-beanstalk>, [">= 0.0.6"])
      s.add_runtime_dependency(%q<hashify>, [">= 0.0.2"])
      s.add_runtime_dependency(%q<hwia>, [">= 1.0.2"])
      s.add_runtime_dependency(%q<twitter-stream>, [">= 0.1.3"])
      s.add_runtime_dependency(%q<dressmaker>, [">= 0.0.3"])
      s.add_runtime_dependency(%q<beanstalk-client>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0"])
      s.add_dependency(%q<em-http-request>, [">= 0.2.6"])
      s.add_dependency(%q<em-beanstalk>, [">= 0.0.6"])
      s.add_dependency(%q<hashify>, [">= 0.0.2"])
      s.add_dependency(%q<hwia>, [">= 1.0.2"])
      s.add_dependency(%q<twitter-stream>, [">= 0.1.3"])
      s.add_dependency(%q<dressmaker>, [">= 0.0.3"])
      s.add_dependency(%q<beanstalk-client>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0"])
    s.add_dependency(%q<em-http-request>, [">= 0.2.6"])
    s.add_dependency(%q<em-beanstalk>, [">= 0.0.6"])
    s.add_dependency(%q<hashify>, [">= 0.0.2"])
    s.add_dependency(%q<hwia>, [">= 1.0.2"])
    s.add_dependency(%q<twitter-stream>, [">= 0.1.3"])
    s.add_dependency(%q<dressmaker>, [">= 0.0.3"])
    s.add_dependency(%q<beanstalk-client>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
  end
end

