development: &default
  search:
    mode: incoming
    adapter: twitter_search
    fetch:
      query:
        q: 'love'
      host: search.twitter.com
      path: search.json
    interval: 10
    
production:
  *default