development: &default
  search:
    mode: incoming
    adapter: twitter_search
    fetch:
      query:
        q: '#sos09'
      host: search.twitter.com
      path: search.json
    interval: 10
  
  twitter:
    mode: [incoming, outgoing]
    adapter: twitter
    username: joshbuddy
    password: testing

production:
  *default