development: &default
  search:
    mode: incoming
    adapter: twitter_search
    fetch:
      query:
        q: '#sos09'
      host: search.twitter.com
      path: search.json
    interval: 10
    status:
      port: 9000
    
  twitter_sender:
    mode: outgoing
    adapter: twitter_sender
    username: joshbuddy
    password: testing
    status:
      port: 9010

production:
  *default